### ISSUE TITLE
Wrap C API

### ISSUE THREAD

**Issue by jramapuram** [arrayfire/arrayfire_rust#4]
currently calls are made along the lines of:

```rust
	unsafe {
          let A: *mut arrayfire::af_array = &mut NULL as *mut _ as *mut arrayfire::af_array;
          let dims: [arrayfire::dim_t; 2] = [5,3];
          arrayfire::af_randu(A, 2, &dims[0], arrayfire::f32);
      }
```

If we can clean this up with a nice 'Rusty' type object that would be helpful.

**Comment by 9prady9** [comment]
@pavanky I think, we can close this as dup of #5  or am i missing something ?

**Comment by jramapuram** [comment]
Sounds good

**Comment by jramapuram** [comment]
Btw, are there any missing operands that still need to be implemented? I.e. all arrayfire C is now in Rust?

**Comment by 9prady9** [comment]
oh, nope :smile: . i only added the following so far:
* functions used in hello world example
* + operator for Array
* Array struct and it's traits implementations
* Dim4 struct

Last three points are essential basis for adding all functions, hence i did them first. Now, we can just keep adding functions one by one. I have an idea about how to organize them.
We can create a module for each header and them the do `use pub` in the `src/lib.rs` file that way, we can have functions cleanly categorized into multiple files instead of single large file and still call the functions by just doing `arrayfire::*` instead of `arrayfire::module::*`
